/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csheets.ext.searcheditcomments;

import csheets.ext.comments.Comment;
import csheets.ext.comments.CommentableCell;
import csheets.ext.comments.CommentableCellListener;
import csheets.ext.comments.CommentsExtension;
import csheets.ui.ctrl.SelectionEvent;
import csheets.ui.ctrl.SelectionListener;
import csheets.ui.ctrl.UIController;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JList;
import javax.swing.JPanel;

/**
 *
 * @author vitoralexandremascarenhasmascarenhas
 */
public class SearchEditCommentPanel extends JPanel implements SelectionListener, CommentableCellListener {
    
    private UIController uiController;
    private JDialog jDialog;
    private SearchCommentsController scc;
    private JDialog jDialogEdit;
    /**
     * @param uiController
     * @param searchCommentController 
     * @param editCommentController 
     * @param jDialog
     * Creates new form SearchEditCommentPanel
     */
    public SearchEditCommentPanel(UIController uiController, JDialog jDialog) {
        this.uiController = uiController;
        this.jDialog = jDialog;
        this.scc = new SearchCommentsController(this.uiController);
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCommentSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblTextSearch = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCommentsResult = new javax.swing.JList();
        btnClose = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        lblNumberIds = new javax.swing.JLabel();
        lblIdValue = new javax.swing.JLabel();
        lblCount = new javax.swing.JLabel();

        txtCommentSearch.setColumns(20);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblTextSearch.setText("Text for Search");

        lstCommentsResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstCommentsResultMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstCommentsResult);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblId.setText("ID");

        lblNumberIds.setText("Number of id's");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtCommentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(lblIdValue)
                        .addGap(53, 53, 53)
                        .addComponent(lblCount))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTextSearch)
                                .addGap(89, 89, 89)
                                .addComponent(lblId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNumberIds)
                                .addGap(22, 22, 22)))))
                .addGap(21, 21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextSearch)
                    .addComponent(lblId)
                    .addComponent(lblNumberIds))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCommentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdValue)
                    .addComponent(lblCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
        String str = txtCommentSearch.getText();
        DefaultListModel dlm = new DefaultListModel();
        DefaultListModel temp = this.scc.searchForExpression(str);
        
        int size = temp.size();
        
        for(int i = 0;i < size; i++) {
            if(temp.get(i).toString().contains(str)) {
                Comment c = (Comment)temp.get(i);
                dlm.addElement(c);
            }
        }
        this.lstCommentsResult.setModel(dlm);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.jDialog.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void lstCommentsResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstCommentsResultMouseClicked
        if(evt.getClickCount() == 2) {
            int index = lstCommentsResult.locationToIndex(evt.getPoint());
            Comment cc = (Comment)lstCommentsResult.getModel().getElementAt(index);
            EditCommentsController ecc = new EditCommentsController(uiController);
            jDialogEdit = new JDialog();
            EditCommentPanel ecp = new EditCommentPanel(uiController, ecc, jDialogEdit, cc);
            jDialogEdit.add(ecp);
            jDialogEdit.setVisible(true);
            jDialogEdit.pack();
        }
        if(evt.getClickCount() == 1) {
            int index = lstCommentsResult.locationToIndex(evt.getPoint());
            CommentableCell cell = (CommentableCell)uiController.getActiveCell().getExtension(CommentsExtension.NAME);
            Comment cc = (Comment)lstCommentsResult.getModel().getElementAt(index);
            lblIdValue.setText(String.valueOf(cc.returnCommentId()));
            lblCount.setText(String.valueOf(cell.returnNumberOfId(cc.returnCommentId())));
            
        }
    }//GEN-LAST:event_lstCommentsResultMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdValue;
    private javax.swing.JLabel lblNumberIds;
    private javax.swing.JLabel lblTextSearch;
    private javax.swing.JList lstCommentsResult;
    private javax.swing.JTextField txtCommentSearch;
    // End of variables declaration//GEN-END:variables

    @Override
    public void selectionChanged(SelectionEvent event) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void commentChanged(CommentableCell cell) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
