/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csheets.lang.files.ui;

import csheets.lang.files.ImportFileController;
import csheets.ui.ctrl.UIController;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Sara Ramos
 */
public class ImportFilePanel extends javax.swing.JPanel
{

    private final UIController uiController;
    private ImportFileController controller;
    private JDialog jDialog;
    private int idSpreadSheet; 
    private boolean readFile = false; //control the sucess of reading file

    /**
     * Creates new form importFilePanel
     *
     * @param uiController
     * @param jDialog
     */
    public ImportFilePanel(UIController uiController, JDialog jDialog)
    {
        this.uiController = uiController;
        this.jDialog = jDialog;
        this.controller = new ImportFileController(uiController);
        initComponents();
        //Group de radiobuttons - only one can be select
        buttonGroup1.add(rdWorkbook);
        buttonGroup1.add(rdSpreadsheet);
        buttonGroup1.add(rdRange); 

        //disable the list of the spreadsheets available and the import button
        cbSpreadsheet.setEnabled(false);
        tfFileName.setEnabled(false);
        rdWorkbook.setEnabled(false);
        rdSpreadsheet.setEnabled(false);
        rdRange.setEnabled(false);
        jtDataArea.setEditable(false);
        btnImportData.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cbSpreadsheet = new javax.swing.JComboBox();
        chooseSpreadsheet = new java.awt.Label();
        rdWorkbook = new javax.swing.JRadioButton();
        rdRange = new javax.swing.JRadioButton();
        rdSpreadsheet = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        btnImportData = new javax.swing.JButton();
        tfFileName = new javax.swing.JLabel();
        btChooseFile = new javax.swing.JButton();
        fileDataArea = new javax.swing.JScrollPane();
        jtDataArea = new javax.swing.JTextArea();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Import file"));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Import data from"));

        cbSpreadsheet.setToolTipText("");
        cbSpreadsheet.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbSpreadsheetActionPerformed(evt);
            }
        });

        chooseSpreadsheet.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        chooseSpreadsheet.setText("Choose spreadsheet ID:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chooseSpreadsheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSpreadsheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbSpreadsheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseSpreadsheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        rdWorkbook.setText("Workbook");
        rdWorkbook.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rdWorkbookActionPerformed(evt);
            }
        });

        rdRange.setText("Range cells");
        rdRange.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rdRangeActionPerformed(evt);
            }
        });

        rdSpreadsheet.setText("Spreadsheet");
        rdSpreadsheet.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rdSpreadsheetActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelButtonActionPerformed(evt);
            }
        });

        btnImportData.setText("Import data");
        btnImportData.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnImportDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnImportData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(btnImportData))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(rdWorkbook)
                        .addGap(18, 18, 18)
                        .addComponent(rdSpreadsheet)
                        .addGap(18, 18, 18)
                        .addComponent(rdRange))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdWorkbook)
                    .addComponent(rdSpreadsheet)
                    .addComponent(rdRange))
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        tfFileName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tfFileName.setText("No file selected");

        btChooseFile.setText("Choose File");
        btChooseFile.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btChooseFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btChooseFile)
                            .addComponent(tfFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btChooseFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        fileDataArea.setBorder(null);
        fileDataArea.setToolTipText("");
        fileDataArea.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("File Data"));

        jtDataArea.setColumns(20);
        jtDataArea.setRows(5);
        fileDataArea.setViewportView(jtDataArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fileDataArea, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fileDataArea))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rdWorkbookActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rdWorkbookActionPerformed
    {//GEN-HEADEREND:event_rdWorkbookActionPerformed
        cbSpreadsheet.setEnabled(false);
        btnImportData.setEnabled(true);
    }//GEN-LAST:event_rdWorkbookActionPerformed

    private void btChooseFileActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btChooseFileActionPerformed
    {//GEN-HEADEREND:event_btChooseFileActionPerformed
        //calls the FileChooser
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter(".xml", "xml"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter(".pdf", "pdf"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter(".docx", "docx"));
        fileChooser.setAcceptAllFileFilterUsed(true);

        int result = fileChooser.showOpenDialog(ImportFilePanel.this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String filePath = selectedFile.getAbsolutePath();
            tfFileName.setText(selectedFile.getName());
         
            //All data from file is "read" - in XML parsed
            try{
                this.readFile = controller.importFile(filePath);
            } catch(IllegalArgumentException ex){
                JOptionPane.showMessageDialog(null, ex);
                if(!ex.toString().contains("The extension of the selected file is not implemented! \nTry another file.")){
                    this.jDialog.dispose();
                }
            }
            
            if(readFile){
                String str;
                    try {
                        byte bt[] = Files.readAllBytes(selectedFile.toPath());
                        str = new String(bt, "UTF-8");
                        jtDataArea.setText(str);
                    } catch (IOException ex) {
                         JOptionPane.showMessageDialog(null, "File is not well formated to show content!");
                         this.jDialog.dispose();
                    }

                    //action on the radio button
                    rdSpreadsheet.setEnabled(true);
                    rdWorkbook.setEnabled(true);
                    rdRange.setEnabled(true);
                    fillCbSpreadsheet();
            }
     
        }
        btnImportData.setEnabled(false);
    }//GEN-LAST:event_btChooseFileActionPerformed

    private void rdSpreadsheetActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rdSpreadsheetActionPerformed
    {//GEN-HEADEREND:event_rdSpreadsheetActionPerformed
        btnImportData.setEnabled(true);
        cbSpreadsheet.setEnabled(true);
    }//GEN-LAST:event_rdSpreadsheetActionPerformed

    private void fillCbSpreadsheet(){
         //clean the previous option added in the combo box of spreadsheets
        cbSpreadsheet.removeAllItems();

        List<Integer> idsList = controller.extractIdsSpreadsheets();
        for (Integer id : idsList) {
            //user can select the id of the spreadsheet
            cbSpreadsheet.addItem(id);
        }
        cbSpreadsheet.setSelectedIndex(0); //first indez by default
    }
            
    private void rdRangeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rdRangeActionPerformed
    {//GEN-HEADEREND:event_rdRangeActionPerformed
        btnImportData.setEnabled(true);
        cbSpreadsheet.setEnabled(true);
    }//GEN-LAST:event_rdRangeActionPerformed

    private void cbSpreadsheetActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbSpreadsheetActionPerformed
    {//GEN-HEADEREND:event_cbSpreadsheetActionPerformed
        this.idSpreadSheet = (Integer)cbSpreadsheet.getSelectedItem();
        btnImportData.setEnabled(true);
    }//GEN-LAST:event_cbSpreadsheetActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
    {//GEN-HEADEREND:event_cancelButtonActionPerformed
        this.jDialog.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void btnImportDataActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnImportDataActionPerformed
    {//GEN-HEADEREND:event_btnImportDataActionPerformed
            
        boolean success = false;
        if (rdWorkbook.isSelected()){
           
            try {
                success = this.controller.replaceData();
            } catch (IllegalArgumentException ex) {
                JOptionPane.showMessageDialog(null, "The data was not imported!");
            }
        }else if(rdSpreadsheet.isSelected()){
            
            try {
                success = this.controller.replaceData("Spreadsheet", this.idSpreadSheet);
            } catch (IllegalArgumentException ex) {
                JOptionPane.showMessageDialog(null, "The data was not imported!");
            }
        }else{
            
            try {
                success = this.controller.replaceData("Range", this.idSpreadSheet);
            } catch (IllegalArgumentException ex) {
                JOptionPane.showMessageDialog(null, "The data was not imported!");
            }
        }
                      
       if(success){
            JOptionPane.showMessageDialog(null, "All data was imported!");
       }
        
        this.jDialog.dispose();
    }//GEN-LAST:event_btnImportDataActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btChooseFile;
    private javax.swing.JButton btnImportData;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox cbSpreadsheet;
    private java.awt.Label chooseSpreadsheet;
    private javax.swing.JScrollPane fileDataArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextArea jtDataArea;
    private javax.swing.JRadioButton rdRange;
    private javax.swing.JRadioButton rdSpreadsheet;
    private javax.swing.JRadioButton rdWorkbook;
    private javax.swing.JLabel tfFileName;
    // End of variables declaration//GEN-END:variables
}
