  @startuml doc-files/lang02_01_analysis_v2.png
 interface Expression<T> {
      
    }
    class TemporalVariable {
    
    }
    class Reference {

    }
    class CellReference {
    }

    Expression <|-- Reference
    Reference <|-- TemporalVariable
    Reference <|-- CellReference
    
  @enduml